export const FONTS_LOADED = 'FONTS_LOADED';
export const RESUME_LOADED = 'DATA_LOADED';


export const SECTION_ENTER = 'SECTION_ENTER';
export const TOGGLE_WELCOME = 'TOGGLE_WELCOME';


export const TOGGLE_PROJECT_MODAL = 'TOGGLE_PROJECT_MODAL';


export const CAROUSEL_INIT = 'CAROUSEL_INIT';
export const CAROUSEL_ROTATE = 'CAROUSEL_ROTATE';
export const CAROUSEL_RESIZE = 'CAROUSEL_RESIZE';
export const CAROUSEL_LOAD_PANELS = 'CAROUSEL_LOAD_PANELS';
